DROP DATABASE IF EXISTS `heroku_5ea03c56b0e78a0`;
CREATE DATABASE IF NOT EXISTS `heroku_5ea03c56b0e78a0`;
USE `heroku_5ea03c56b0e78a0`;

DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `id` INT(11) AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS task;
CREATE TABLE task (
  `id` INT(11) AUTO_INCREMENT PRIMARY KEY,
  `author_id` INTEGER NOT NULL,
  `content` TEXT NOT NULL,
  `done` boolean DEFAULT false,
  FOREIGN KEY (`author_id`) REFERENCES `user` (`id`)
);
